//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Consulting.WorkflowStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Consulting.WorkflowStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Workflow aborted.
        /// </summary>
        public static string AbortedInDebugStatus {
            get {
                return ResourceManager.GetString("AbortedInDebugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Workflow aborted.
        /// </summary>
        public static string AbortedStatus {
            get {
                return ResourceManager.GetString("AbortedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Workflow aborting ....
        /// </summary>
        public static string AbortingInDebugStatus {
            get {
                return ResourceManager.GetString("AbortingInDebugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Workflow aborting ....
        /// </summary>
        public static string AbortingServiceHostStatus {
            get {
                return ResourceManager.GetString("AbortingServiceHostStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Workflow aborting ....
        /// </summary>
        public static string AbortingStatus {
            get {
                return ResourceManager.GetString("AbortingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Workflow Studio
        ///Copyright (c) Microsoft Corporation. All rights reserved.
        ///Version {0}.
        /// </summary>
        public static string AboutDialogMessage {
            get {
                return ResourceManager.GetString("AboutDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string AboutDialogTitle {
            get {
                return ResourceManager.GetString("AboutDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Workflow service host closed.
        /// </summary>
        public static string ClosedServiceHostInDebugStatus {
            get {
                return ResourceManager.GetString("ClosedServiceHostInDebugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Workflow service host closed.
        /// </summary>
        public static string ClosedServiceHostStatus {
            get {
                return ResourceManager.GetString("ClosedServiceHostStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Collection.
        /// </summary>
        public static string CollectionCategoryToToolbox {
            get {
                return ResourceManager.GetString("CollectionCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Workflow completed with completion state {0}.
        /// </summary>
        public static string CompletedInDebugStatus {
            get {
                return ResourceManager.GetString("CompletedInDebugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Workflow completed with completion state {0}.
        /// </summary>
        public static string CompletedStatus {
            get {
                return ResourceManager.GetString("CompletedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This workflow is running. Do you wish to exit?.
        /// </summary>
        public static string ConfirmCloseWhenRunningWorkflowDialogMessage {
            get {
                return ResourceManager.GetString("ConfirmCloseWhenRunningWorkflowDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string ConfirmCloseWhenRunningWorkflowDialogTitle {
            get {
                return ResourceManager.GetString("ConfirmCloseWhenRunningWorkflowDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are one or more running workflows. Do you wish to close?.
        /// </summary>
        public static string ConfirmCloseWhenRunningWorkflowsDialogMessage {
            get {
                return ResourceManager.GetString("ConfirmCloseWhenRunningWorkflowsDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string ConfirmCloseWhenRunningWorkflowsDialogTitle {
            get {
                return ResourceManager.GetString("ConfirmCloseWhenRunningWorkflowsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save changes to {0}.
        /// </summary>
        public static string ConfirmSaveDialogMessage {
            get {
                return ResourceManager.GetString("ConfirmSaveDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Changes.
        /// </summary>
        public static string ConfirmSaveDialogTitle {
            get {
                return ResourceManager.GetString("ConfirmSaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control Flow.
        /// </summary>
        public static string ControlFlowCategoryToToolbox {
            get {
                return ResourceManager.GetString("ControlFlowCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debugging workflow ....
        /// </summary>
        public static string DebuggingStatus {
            get {
                return ResourceManager.GetString("DebuggingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _Debug.
        /// </summary>
        public static string DebugMenu {
            get {
                return ResourceManager.GetString("DebugMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abort.
        /// </summary>
        public static string DebugMenuAbort {
            get {
                return ResourceManager.GetString("DebugMenuAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Debugging.
        /// </summary>
        public static string DebugMenuStartDebugging {
            get {
                return ResourceManager.GetString("DebugMenuStartDebugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;F5&apos;.
        /// </summary>
        public static string DebugMenuStartDebuggingCommandKey {
            get {
                return ResourceManager.GetString("DebugMenuStartDebuggingCommandKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string DebugMenuStartDebuggingCommandModifier {
            get {
                return ResourceManager.GetString("DebugMenuStartDebuggingCommandModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Without Debugging.
        /// </summary>
        public static string DebugMenuStartWithoutDebugging {
            get {
                return ResourceManager.GetString("DebugMenuStartWithoutDebugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &apos;F5&apos;.
        /// </summary>
        public static string DebugMenuStartWithoutDebuggingCommandKey {
            get {
                return ResourceManager.GetString("DebugMenuStartWithoutDebuggingCommandKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Control.
        /// </summary>
        public static string DebugMenuStartWithoutDebuggingCommandModifier {
            get {
                return ResourceManager.GetString("DebugMenuStartWithoutDebuggingCommandModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string DialogCaptionError {
            get {
                return ResourceManager.GetString("DialogCaptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error Handling.
        /// </summary>
        public static string ErrorHandlingCategoryToToolbox {
            get {
                return ResourceManager.GetString("ErrorHandlingCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error occurred loading document
        ///
        ///{0}.
        /// </summary>
        public static string ErrorLoadingDialogMessage {
            get {
                return ResourceManager.GetString("ErrorLoadingDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string ErrorLoadingDialogTitle {
            get {
                return ResourceManager.GetString("ErrorLoadingDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error occurred loading document
        ///
        ///{0}.
        /// </summary>
        public static string ErrorLoadingInDebugDialogMessage {
            get {
                return ResourceManager.GetString("ErrorLoadingInDebugDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string ErrorLoadingInDebugDialogTitle {
            get {
                return ResourceManager.GetString("ErrorLoadingInDebugDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error occurred running workflow
        ///
        ///{0}.
        /// </summary>
        public static string ErrorRunningDialogMessage {
            get {
                return ResourceManager.GetString("ErrorRunningDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string ErrorRunningDialogTitle {
            get {
                return ResourceManager.GetString("ErrorRunningDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string ErrorValidationItem {
            get {
                return ResourceManager.GetString("ErrorValidationItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Workflow exception, see output window for stack trace.
        /// </summary>
        public static string ExceptionInDebugStatus {
            get {
                return ResourceManager.GetString("ExceptionInDebugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Workflow exception, see output window for stack trace.
        /// </summary>
        public static string ExceptionServiceHostStatus {
            get {
                return ResourceManager.GetString("ExceptionServiceHostStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Workflow exception, see output window for stack trace.
        /// </summary>
        public static string ExceptionStatus {
            get {
                return ResourceManager.GetString("ExceptionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Workflow exception, see output window for stack trace.
        /// </summary>
        public static string ExceptionWhenRunningInDebugStatus {
            get {
                return ResourceManager.GetString("ExceptionWhenRunningInDebugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Workflow service host faulted.
        /// </summary>
        public static string FaultedServiceHostInDebugStatus {
            get {
                return ResourceManager.GetString("FaultedServiceHostInDebugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Workflow service host faulted.
        /// </summary>
        public static string FaultedServiceHostStatus {
            get {
                return ResourceManager.GetString("FaultedServiceHostStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _File.
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Reference ....
        /// </summary>
        public static string FileMenuAddReference {
            get {
                return ResourceManager.GetString("FileMenuAddReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string FileMenuClose {
            get {
                return ResourceManager.GetString("FileMenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close All.
        /// </summary>
        public static string FileMenuCloseAll {
            get {
                return ResourceManager.GetString("FileMenuCloseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string FileMenuExit {
            get {
                return ResourceManager.GetString("FileMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Service ....
        /// </summary>
        public static string FileMenuNewService {
            get {
                return ResourceManager.GetString("FileMenuNewService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Workflow ....
        /// </summary>
        public static string FileMenuNewWorkflow {
            get {
                return ResourceManager.GetString("FileMenuNewWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open ....
        /// </summary>
        public static string FileMenuOpen {
            get {
                return ResourceManager.GetString("FileMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string FileMenuSave {
            get {
                return ResourceManager.GetString("FileMenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save All.
        /// </summary>
        public static string FileMenuSaveAll {
            get {
                return ResourceManager.GetString("FileMenuSaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save As ....
        /// </summary>
        public static string FileMenuSaveAs {
            get {
                return ResourceManager.GetString("FileMenuSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flowchart.
        /// </summary>
        public static string FlowchartCategoryToToolbox {
            get {
                return ResourceManager.GetString("FlowchartCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _Help.
        /// </summary>
        public static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string HelpMenuAbout {
            get {
                return ResourceManager.GetString("HelpMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Workflow Studio.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Messaging.
        /// </summary>
        public static string MessagingCategoryToToolbox {
            get {
                return ResourceManager.GetString("MessagingCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New workflow {0}.
        /// </summary>
        public static string NewWorkflowTabTitle {
            get {
                return ResourceManager.GetString("NewWorkflowTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New workflow {0} {1}.
        /// </summary>
        public static string NewWorkflowWithModifierTabTitle {
            get {
                return ResourceManager.GetString("NewWorkflowWithModifierTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Workflow service host opened.
        /// </summary>
        public static string OpenServiceHostInDebugStatus {
            get {
                return ResourceManager.GetString("OpenServiceHostInDebugStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Workflow service host opened.
        /// </summary>
        public static string OpenServiceHostStatus {
            get {
                return ResourceManager.GetString("OpenServiceHostStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primitives.
        /// </summary>
        public static string PrimitivesCategoryToToolbox {
            get {
                return ResourceManager.GetString("PrimitivesCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ready.
        /// </summary>
        public static string ReadyStatus {
            get {
                return ResourceManager.GetString("ReadyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Workflow running ....
        /// </summary>
        public static string RunningStatus {
            get {
                return ResourceManager.GetString("RunningStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Runtime.
        /// </summary>
        public static string RuntimeCategoryToToolbox {
            get {
                return ResourceManager.GetString("RuntimeCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save changes to following workflows?
        ///{0}.
        /// </summary>
        public static string SaveChangesDialogMessage {
            get {
                return ResourceManager.GetString("SaveChangesDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Changes.
        /// </summary>
        public static string SaveChangesDialogTitle {
            get {
                return ResourceManager.GetString("SaveChangesDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save successful.
        /// </summary>
        public static string SaveSuccessfulStatus {
            get {
                return ResourceManager.GetString("SaveSuccessfulStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saving workflow ....
        /// </summary>
        public static string SavingStatus {
            get {
                return ResourceManager.GetString("SavingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transaction.
        /// </summary>
        public static string TransactionCategoryToToolbox {
            get {
                return ResourceManager.GetString("TransactionCategoryToToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unhandled exception occurred, see log for details : {0}.
        /// </summary>
        public static string UnhandledExceptionMessage {
            get {
                return ResourceManager.GetString("UnhandledExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unhandled exception occurred on {0} : {1}.
        /// </summary>
        public static string UnhandledExceptionTrace {
            get {
                return ResourceManager.GetString("UnhandledExceptionTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _View.
        /// </summary>
        public static string ViewMenu {
            get {
                return ResourceManager.GetString("ViewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debug.
        /// </summary>
        public static string ViewMenuDebug {
            get {
                return ResourceManager.GetString("ViewMenuDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errors.
        /// </summary>
        public static string ViewMenuErrors {
            get {
                return ResourceManager.GetString("ViewMenuErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Outline.
        /// </summary>
        public static string ViewMenuOutline {
            get {
                return ResourceManager.GetString("ViewMenuOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Output.
        /// </summary>
        public static string ViewMenuOutput {
            get {
                return ResourceManager.GetString("ViewMenuOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Properties.
        /// </summary>
        public static string ViewMenuProperties {
            get {
                return ResourceManager.GetString("ViewMenuProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toolbox.
        /// </summary>
        public static string ViewMenuToolbox {
            get {
                return ResourceManager.GetString("ViewMenuToolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        public static string WarningValidationItem {
            get {
                return ResourceManager.GetString("WarningValidationItem", resourceCulture);
            }
        }
    }
}
